import axios from "axios"
import {useQuery} from "@tanstack/react-query"

function replaceWithBr(str) {
  return str.replace(/\n/g, "<br />")
}

export const single = async (conversation) => {
  console.log(conversation)
    const response = await axios.post(
      "https://api.openai.com/v1/chat/completions",
      {
        "model": "gpt-3.5-turbo",
        "messages": conversation,
        "temperature": 0.7
      },
      {
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer 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`,
        },
      }
    );
    return [...conversation, {
      "role": response.data.choices[0].message.role,
      "content": replaceWithBr(response.data.choices[0].message.content)
    }];/*
    return [
      {
          "role": "system",
          "content": "You are a Expert Content Creator for Instagram page."
      },
      {
          "role": "assistant",
          "content": "Hello, I'm Abby, your own seasoned content creator. I will help you craft Instagram content that not only resonates with your audience but also converts them into paying customers."
      },
      {
          "role": "assistant",
          "content": "Tell me about your business, its mission, vision, and target audience. The more you share, the better I can tailor content ideas to your unique brand identity and customer needs."
      },
      {
          "role": "system",
          "content": "You will get the details from the user and give him 3 content ideas and do not make them long. After that ask the user to choose an idea and you will generate captions for 1 posts using it. Your results should be in this format: \"InstaPostStart <caption> InstaPostEnd\" do not add anything else"
      },
      {
          "role": "user",
          "content": "My company uses AI to make art"
      },
      {
          "role": "assistant",
          "content": "Great! Here are three content ideas for your Instagram page:<br /><br />1. Showcasing Art: Share art pieces generated by your AI and the stories behind them. For instance, how the technology works, the inspiration behind each piece, and the techniques that were used to create them. You can also share how your AI differs from traditional art techniques and the benefits of using it. <br /><br />2. Behind the Scenes: Give your audience a sneak peek into the process of creating AI-generated art. Share short videos or images of the technology at work, the team working behind the scenes, and the tools and software used to create the art.<br /><br />3. Interactive Art: Create an interactive experience for your followers by inviting them to participate in creating AI-generated art. For example, you can ask them to submit images or patterns that your AI can incorporate in its art pieces, or you can run contests where followers can win an AI-generated art piece.<br /><br />Please choose one of these ideas, and I will generate a caption for one post using it."
      },
      {
          "role": "user",
          "content": "third one"
      },
      {
          "role": "assistant",
          "content": "Great choice! Here's a caption for a post showcasing an interactive art experience:<br /><br />InstaPostStart<br />🎨 Create Art with AI 🤖<br /><br />We're excited to invite you to participate in our latest interactive art experience! To join in, simply share an image or pattern that you'd like to see incorporated in an AI-generated art piece. Our technology will bring your vision to life, resulting in a unique and one-of-a-kind art piece that you can call your own. 🎉<br /><br />To participate, follow these simple steps:<br /><br />1️⃣ Share an image or pattern you'd like to see in our art piece<br />2️⃣ Tag us in the post and use the hashtag #CreateArtWithAI<br />3️⃣ We'll choose one lucky participant to receive an AI-generated art piece!<br /><br />We can't wait to see what you come up with! 🎨🤖<br /><br />InstaPostEnd"
      }
  ]*/
    //return prompt
};

export const campaign = async (conversation) => {
    const response = await axios.post(
      "https://api.openai.com/v1/chat/completions",
      {
        "model": "gpt-3.5-turbo",
        "messages": conversation,
        "temperature": 0.7
      },
      {
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer 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`,
        },
      }
    );
  
    return [...conversation, {
      "role": response.data.choices[0].message.role,
      "content": replaceWithBr(response.data.choices[0].message.content)
    }];
};